### ISSUE TITLE
Cannot run Migrado using latest docker image

### ISSUE THREAD

**Issue by Nargonath** [protojour/migrado#8]
Thank you for the project. Sorry if this is a stupid error as I have 0 Python knowledge. Let me know if I need to configure something on my end.

I want to use the Migrado docker image to run the binary. I ran `docker run protojour/migrado --help` on my laptop. Here is the result:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/migrado.py", line 13, in <module>
    from .constants import MIGRATION_TEMPLATE
ImportError: attempted relative import with no known parent package
```

Let me know if you need more information. Thank you for your help.

**Comment by tangram** [comment]
Hi, sorry for not getting back to you sooner. There was a misconfiguration in the `Dockerfile`. I've now rebuilt the image and published the new version to Docker Hub. It should now work as expected, run `docker pull protojour/migrado` if it doesn't happen automatically.

**Comment by Nargonath** [comment]
Alright, thank you. In the meantime I ended up writing my own Dockerfile to upgrade to the latest version and simplify it a little bit. I can submit a PR if you want.
